### ISSUE TITLE
Undefined array key warning in addnewpage/syntax.php line 66

### ISSUE THREAD

**Issue by dregad** [dregad/dokuwiki-plugin-addnewpage#91]
Occurs on a page with `{{NEWPAGE>namespace}}` tag, i.e. not using the `#` template option.

Back trace:
```#0 .../addnewpage/syntax.php(66): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '.../d...', 66)
#1 .../inc/parser/handler.php(284): syntax_plugin_addnewpage->handle('{{NEWPAGE>activ...', 5, 229, Object(Doku_Handler))
#2 .../inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('{{NEWPAGE>activ...', 5, 229, 'addnewpage')
#3 .../inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('{{NEWPAGE>activ...', 5, 229)
#4 .../inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '{{NEWPAGE>activ...', '_plugin_addnewp...', 229, 229)
#5 .../inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse(' \\\\\n\n[[c_templa...')
#6 .../inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n====== Fiches ...')
#7 .../inc/parserutils.php(198): p_get_instructions('====== Fiches d...')
#8 .../inc/parserutils.php(525): p_cached_instructions('.../w...', false, 'activites:start')
#9 .../inc/parserutils.php(299): p_render_metadata('activites:start', Array)
#10 .../inc/common.php(266): p_get_metadata('activites:start')
#11 .../doku.php(97): pageinfo()
#12 {main}
```

This is with PHP 8.2 and DokuWiki Jack Jackrum release

**Comment by landryb** [comment]
thanks for the PR #92, can confirm this definitely fixes the warning here
